import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const english = {
  'Nutrição sem complicações': 'Nutrition made simple', 'Resumo': 'Overview', 'Receitas': 'Recipes', 'Diário': 'Diary', 'Definições': 'Settings', 'Terminar sessão': 'Sign out',
  'O teu dia nutricional': 'Your nutrition today', 'Olá! O que vamos comer?': 'Hello! What are we eating?', 'Acompanha as refeições e mantém os teus objetivos à vista.': 'Track your meals and keep your goals in sight.', 'Registar refeição': 'Log meal', 'Calorias restantes': 'Calories remaining', 'Consumiste {{consumed}} das {{goal}} kcal planeadas.': 'You consumed {{consumed}} of {{goal}} planned kcal.', 'Macronutrientes': 'Macronutrients', 'Proteína': 'Protein', 'Hidratos': 'Carbs', 'Gordura': 'Fat', 'Refeições de hoje': "Today's meals", '{{count}} registo(s)': '{{count}} entry', '{{count}} registo(s)_plural': '{{count}} entries', 'Ainda não registaste nenhuma refeição.': "You haven't logged any meals yet.", 'Ver diário': 'View diary', 'Pesquisa uma receita para começares o teu dia.': 'Find a recipe to start your day.', '{{count}} porção(ões)': '{{count}} serving', '{{count}} porção(ões)_plural': '{{count}} servings',
  'Histórico': 'History', 'Diário de refeições': 'Meal diary', 'Consulta e gere tudo o que registaste.': 'View and manage everything you have logged.', 'Compras': 'Shopping', 'Planeamento': 'Planning', 'Lista de compras': 'Shopping list', 'Adiciona as refeições que queres comprar a partir da vista semanal do diário.': 'Add the meals you want to shop for from the weekly diary view.', '{{count}} refeição(ões) adicionada(s)': '{{count}} meal added', '{{count}} refeição(ões) adicionada(s)_plural': '{{count}} meals added', '{{count}} refeição(ões) adicionada(s) à lista de compras.': '{{count}} meal added to your shopping list.', '{{count}} refeição(ões) adicionada(s) à lista de compras._plural': '{{count}} meals added to your shopping list.', '{{count}} ingrediente(s) na lista': '{{count}} ingredient on the list', '{{count}} ingrediente(s) na lista_plural': '{{count}} ingredients on the list', '{{count}} receita(s) planeada(s)': '{{count}} planned recipe', '{{count}} receita(s) planeada(s)_plural': '{{count}} planned recipes', 'Por receita': 'By recipe', 'Limpar itens assinalados': 'Clear checked items', 'Limpar lista': 'Clear list', 'A lista de compras está vazia': 'Your shopping list is empty', 'Abre a vista semanal do diário e adiciona as refeições futuras que queres comprar.': 'Open the weekly diary view and add the future meals you want to shop for.', 'Adicionar semana às compras': 'Add week to shopping list', 'Não existem refeições futuras nesta semana.': 'There are no future meals this week.', 'Ainda não tens refeições planeadas': 'You do not have any planned meals yet', 'Regista receitas numa data futura para criares automaticamente a lista de compras.': 'Log recipes on a future date to automatically create your shopping list.', 'Ver receitas': 'View recipes', 'Marcar ingrediente {{name}}': 'Mark {{name}}', 'Ingredientes com g, kg, ml ou L são somados automaticamente quando o nome é igual.': 'Ingredients with g, kg, ml or L are automatically totalled when their name matches.', 'Calorias': 'Calories', 'Sem registos.': 'No entries.', 'Editar registo': 'Edit entry', 'Remover refeição': 'Remove meal', 'Não foi possível apagar o registo.': 'Could not delete the entry.',
  'Adicionar refeição': 'Add meal', 'Pesquisar receitas': 'Search recipes', 'Refeição manual': 'Manual meal', 'Manual': 'Manual', 'Nome da refeição': 'Meal name', 'Valores introduzidos manualmente.': 'Values entered manually.', 'Os macros são opcionais. Se não os souberes, podes deixar em branco.': 'Macros are optional. Leave them blank if you do not know them.', 'Indica o nome e as calorias da refeição.': 'Enter the meal name and calories.', 'Introduz valores nutricionais válidos.': 'Enter valid nutritional values.', 'Estimar com IA': 'Estimate with AI', 'Descreve o que comeste e a IA preenche uma estimativa que podes alterar antes de guardar.': 'Describe what you ate and AI will fill in an estimate that you can edit before saving.', 'Ex.: comi uma sandes de frango grelhado com queijo e um galão.': 'E.g. I had a grilled chicken and cheese sandwich and a latte.', 'A estimar...': 'Estimating...', 'Estimar valores': 'Estimate values', 'Descreve primeiro o que comeste.': 'Describe what you ate first.', 'Não foi possível obter uma estimativa agora.': 'Could not get an estimate right now.', 'A estimativa por IA só está disponível no ambiente Vercel. Faz deploy ou inicia com vercel dev.': 'AI estimation is only available in the Vercel environment. Deploy the app or start it with vercel dev.', 'Pesquisa uma receita para registar no diário.': 'Search for a recipe to log in your diary.', 'Nenhuma receita encontrada.': 'No recipes found.',
  'Favoritas': 'Favorites', 'Adicionar aos favoritos': 'Add to favorites', 'Remover dos favoritos': 'Remove from favorites', 'Não foi possível atualizar os favoritos.': 'Could not update favorites.', 'Ordenar por': 'Sort by', 'Mais recentes': 'Most recent', 'Preparação mais rápida': 'Quickest preparation', 'Mais calorias': 'Most calories', 'Menos calorias': 'Fewest calories', 'Mais proteína': 'Most protein', 'Menos proteína': 'Least protein',
  'Peso inicial (kg)': 'Starting weight (kg)', 'Peso guardado e objetivos recalculados.': 'Weight saved and goals recalculated.', 'Peso guardado e objetivo de água atualizado.': 'Weight saved and water goal updated.', 'Não foi possível atualizar os objetivos.': 'Could not update goals.', 'Medidas corporais (opcional)': 'Body measurements (optional)', 'Cintura (cm)': 'Waist (cm)', 'Anca (cm)': 'Hips (cm)', 'Abdominal (cm)': 'Abdomen (cm)', 'Braço (cm)': 'Arm (cm)', 'Coxa (cm)': 'Thigh (cm)', 'Gémeo (cm)': 'Calf (cm)', 'Guardar registo': 'Save entry',
  'Progresso': 'Progress', 'Histórico de peso': 'Weight history', 'Regista o teu peso e acompanha a evolução ao longo do tempo.': 'Log your weight and track your progress over time.', 'Evolução': 'Progress', 'Sem registos ainda': 'No entries yet', 'Registos': 'Entries', 'Variação': 'Change', 'Adicionar registo': 'Add entry', 'Data': 'Date', 'Peso (kg)': 'Weight (kg)', 'Guardar peso': 'Save weight', 'Peso guardado com sucesso.': 'Weight saved successfully.', 'Ainda não existem registos de peso.': 'There are no weight entries yet.', 'Apagar registo de peso': 'Delete weight entry', 'Adiciona pelo menos dois registos\npara veres o gráfico.': 'Add at least two entries\nto see the chart.',
  'Sugestões para o jantar': 'Dinner suggestions', 'Receitas escolhidas com base no que falta para os teus objetivos de hoje.': 'Recipes selected based on what is left to reach your goals today.',
  'Água': 'Water', '{{consumed}} ml de {{goal}} ml': '{{consumed}} ml of {{goal}} ml', '{{count}} movimento(s)': '{{count}} entry', '{{count}} movimento(s)_plural': '{{count}} entries', 'Apagar registo de água': 'Delete water entry', 'Não foi possível apagar o registo de água.': 'Could not delete the water entry.', 'Ainda não registaste água neste dia.': 'You have not logged water for this day yet.', 'Outro valor': 'Other amount', 'Adicionar água': 'Add water', 'Quantidade de água (ml)': 'Water amount (ml)', 'Introduz uma quantidade de água válida.': 'Enter a valid water amount.', 'Não foi possível atualizar a água.': 'Could not update water intake.', 'Objetivo diário de água': 'Daily water goal', 'Define a quantidade de água que queres acompanhar todos os dias.': 'Set the amount of water you want to track every day.', 'Água por dia (ml)': 'Water per day (ml)', 'Guardar objetivo de água': 'Save water goal', 'Objetivo de água guardado.': 'Water goal saved.', 'Não foi possível guardar o objetivo de água.': 'Could not save water goal.',
  'Não podes guardar registos em datas futuras.': 'You cannot save entries for future dates.', 'Variação das medidas': 'Measurement changes', 'Partilhar': 'Share', 'Editar registo de progresso': 'Edit progress entry', 'Cancelar': 'Cancel',
  'Porções para a lista': 'Servings for shopping list', 'Aumentar porções': 'Increase servings', 'Reduzir porções': 'Decrease servings', 'porções na lista': 'servings in list',
  'Adicionar à lista de compras': 'Add to shopping list', 'Receita adicionada à lista de compras.': 'Recipe added to the shopping list.', 'Não foi possível adicionar a receita à lista de compras.': 'Could not add the recipe to the shopping list.', 'Adicionada diretamente': 'Added directly', 'Remover receita da lista': 'Remove recipe from list', 'Fruta e legumes': 'Fruit and vegetables', 'Laticínios e ovos': 'Dairy and eggs', 'Carne, peixe e alternativas': 'Meat, fish and alternatives', 'Cereais e padaria': 'Grains and bakery', 'Despensa': 'Pantry', 'Outros': 'Other',
  'Pequeno-almoço': 'Breakfast', 'Almoço': 'Lunch', 'Lanche': 'Snack', 'Jantar': 'Dinner', 'Pequeno Almoço': 'Breakfast', 'Almoço/Jantar': 'Lunch/Dinner', 'Snacks': 'Snacks', 'Sobremesas': 'Desserts',
  'Dia da refeição': 'Meal date', 'Hoje': 'Today', 'Ontem': 'Yesterday', 'Como ainda é antes das 04:00, sugerimos o dia anterior. Podes alterar se necessário.': 'Since it is before 4:00 AM, we suggest the previous day. You can change it if needed.', 'Tipo de refeição': 'Meal type', 'Número de porções': 'Number of servings', 'proteína': 'protein', 'hidratos': 'carbs', 'gordura': 'fat', 'Registo alterado com sucesso.': 'Entry updated successfully.', 'Refeição registada com sucesso.': 'Meal logged successfully.', 'Não foi possível registar a refeição.': 'Could not log the meal.', 'Alterações guardadas': 'Changes saved', 'Registado': 'Logged', 'Guardar alterações': 'Save changes', 'Adicionar ao diário': 'Add to diary',
  'Biblioteca': 'Library', 'Encontra a próxima refeição': 'Find your next meal', 'Pesquisa pelo nome da receita ou por um ingrediente.': 'Search by recipe name or ingredient.', 'Nova receita': 'New recipe', 'Ex.: frango, aveia, salmão...': 'E.g. chicken, oats, salmon...', 'Todas': 'All', '{{count}} receita(s) encontrada(s)': '{{count}} recipe found', '{{count}} receita(s) encontrada(s)_plural': '{{count}} recipes found', 'A carregar receitas...': 'Loading recipes...', 'Ainda não existem receitas': 'There are no recipes yet', 'Cria a primeira receita para começares.': 'Create the first recipe to get started.', 'Ver': 'View', 'Registar': 'Log', 'Ver receita {{name}}': 'View {{name}} recipe', 'Editar receita': 'Edit recipe', 'Apagar receita': 'Delete recipe', 'A apagar...': 'Deleting...', 'Apagar “{{name}}”?': 'Delete “{{name}}”?', 'Não foi possível apagar.': 'Could not delete.', 'Já existe uma receita com este nome.': 'A recipe with this name already exists.',
  'Voltar às receitas': 'Back to recipes', 'Editar': 'Edit', 'Ingredientes': 'Ingredients', 'Preparação': 'Method', 'Observações': 'Notes', 'Ainda não foram adicionadas instruções de preparação.': 'No preparation instructions have been added yet.', 'A carregar receita...': 'Loading recipe...',
  'Avaliações': 'Reviews', 'Ainda não existem avaliações.': 'There are no reviews yet.', 'Sê a primeira pessoa a avaliar esta receita.': 'Be the first to review this recipe.', '{{average}} de 5 · {{count}} avaliação(ões)': '{{average}} out of 5 · {{count}} review', '{{average}} de 5 · {{count}} avaliação(ões)_plural': '{{average}} out of 5 · {{count}} reviews', 'Avalia esta receita': 'Rate this recipe', 'Editar a tua avaliação': 'Edit your review', 'Comentário (opcional)': 'Comment (optional)', 'Partilha a tua opinião sobre esta receita...': 'Share your thoughts about this recipe...', 'Guardar avaliação': 'Save review', 'Apagar avaliação': 'Delete review', 'Apagar a tua avaliação?': 'Delete your review?', 'Avaliação guardada com sucesso.': 'Review saved successfully.', 'Avaliação apagada.': 'Review deleted.', 'Não foi possível guardar a avaliação.': 'Could not save the review.', 'Não foi possível apagar a avaliação.': 'Could not delete the review.', 'Escolhe uma avaliação entre 1 e 5 estrelas.': 'Choose a rating between 1 and 5 stars.', '{{count}} estrelas': '{{count}} stars', 'Tu': 'You',
  'Cria uma receita': 'Create a recipe', 'Nome': 'Name', 'Categoria': 'Category', 'Tipo': 'Type', 'Doce': 'Sweet', 'Salgada': 'Savoury', 'Tempo de preparação (min)': 'Preparation time (min)', 'Imagem da receita': 'Recipe image', '(opcional)': '(optional)', 'Opcional': 'Optional', 'Pré-visualização da receita': 'Recipe preview', 'Remover imagem': 'Remove image', 'Escolher uma imagem': 'Choose a recipe image', 'JPEG, PNG ou WebP · máximo 5 MB': 'JPEG, PNG or WebP · maximum 5 MB', 'Substituir imagem': 'Replace image', 'Valores por porção': 'Values per serving', 'Adicionar': 'Add', 'Quantidade': 'Quantity', 'Unidade': 'Unit', 'Ingrediente (PT)': 'Ingredient (PT)', 'Ingrediente (EN)': 'Ingredient (EN)', 'Ingrediente {{number}}': 'Ingredient {{number}}', 'Descreve os passos de preparação...': 'Describe the preparation steps...', 'Tornar receita pública': 'Make recipe public', 'Outros utilizadores poderão encontrá-la, mas apenas tu poderás alterá-la.': 'Other users will be able to find it, but only you can edit it.', 'A guardar...': 'Saving...', 'Criar receita': 'Create recipe', 'A autenticação não está configurada.': 'Authentication is not configured.', 'A tua sessão expirou. Inicia sessão novamente.': 'Your session has expired. Sign in again.', 'Não foi possível guardar a receita.': 'Could not save the recipe.', 'Escolhe uma imagem JPEG, PNG ou WebP.': 'Choose a JPEG, PNG or WebP image.', 'A imagem não pode ter mais de 5 MB.': 'The image cannot exceed 5 MB.',
  'Preferências': 'Preferences', 'Atualiza os teus dados, recalcula o plano ou define objetivos manualmente.': 'Update your details, recalculate your plan or set goals manually.', 'Vamos personalizar o teu plano': "Let's personalize your plan", 'Responde a algumas perguntas para estimarmos os teus objetivos.': 'Answer a few questions so we can estimate your goals.', 'Criar o meu plano': 'Create my plan',
  'Ano de nascimento': 'Year of birth', 'Fórmula metabólica': 'Metabolic formula', 'Feminina': 'Female', 'Masculina': 'Male', 'Altura (cm)': 'Height (cm)', 'Peso atual (kg)': 'Current weight (kg)', 'Nível de atividade': 'Activity level', 'Sedentário': 'Sedentary', 'Ligeiramente ativo (1–3 dias/semana)': 'Lightly active (1–3 days/week)', 'Moderadamente ativo (3–5 dias/semana)': 'Moderately active (3–5 days/week)', 'Muito ativo (6–7 dias/semana)': 'Very active (6–7 days/week)', 'Extremamente ativo': 'Extremely active', 'Objetivo': 'Goal', 'Perder peso gradualmente': 'Lose weight gradually', 'Manter o peso': 'Maintain weight', 'Ganhar peso gradualmente': 'Gain weight gradually', 'Como queres definir os teus objetivos diários?': 'How would you like to set your daily goals?', 'Podemos estimá-los com as respostas acima ou podes introduzir um plano que já tenhas definido.': 'We can estimate them from your answers or you can enter an existing plan.', 'Calcular por mim': 'Calculate for me', 'Usar idade, corpo, atividade e objetivo.': 'Use age, body, activity and goal.', 'Já tenho valores definidos': 'I already have target values', 'Introduzir calorias e macros manualmente.': 'Enter calories and macros manually.', 'Os teus objetivos diários': 'Your daily goals', 'Objetivos diários estimados': 'Estimated daily goals', 'Introduz os valores do teu plano atual.': 'Enter the values from your current plan.', 'Calculados a partir das respostas acima.': 'Calculated from the answers above.', 'Ao alterar as calorias, proteína, hidratos e gordura são recalculados com base no teu peso e na nova meta calórica. Depois podes editar cada macro individualmente.': 'When calories change, protein, carbs and fat are recalculated using your weight and new calorie target. You can then edit each macro individually.', 'Estimativa para adultos saudáveis baseada em equações populacionais. Necessidades reais podem variar; gravidez, amamentação, condições clínicas ou histórico de perturbações alimentares requerem acompanhamento profissional.': 'Estimate for healthy adults based on population equations. Actual needs may vary; pregnancy, breastfeeding, medical conditions or a history of eating disorders require professional guidance.', 'Alterações guardadas com sucesso.': 'Changes saved successfully.', 'Não foi possível guardar as alterações.': 'Could not save changes.', 'Fechar notificação': 'Close notification',
  'Bem-vinda de volta': 'Welcome back', 'Cria a tua conta': 'Create your account', 'Iniciar sessão': 'Sign in', 'Começar agora': 'Get started', 'Acede às tuas receitas e ao diário de refeições.': 'Access your recipes and meal diary.', 'Guarda os teus objetivos e acompanha cada refeição.': 'Save your goals and track every meal.', 'O teu nome': 'Your name', 'Palavra-passe': 'Password', 'Mínimo de 8 caracteres': 'At least 8 characters', 'Esconder palavra-passe': 'Hide password', 'Mostrar palavra-passe': 'Show password', 'Entrar': 'Sign in', 'Criar conta': 'Create account', 'Ainda não tens conta?': "Don't have an account yet?", 'Já tens uma conta?': 'Already have an account?', 'Regista-te': 'Sign up', 'Inicia sessão': 'Sign in', 'Não foi possível contactar o serviço de autenticação. Tenta novamente.': 'Could not contact the authentication service. Try again.', 'Email ou palavra-passe incorretos.': 'Incorrect email or password.', 'Já existe uma conta com este email.': 'An account with this email already exists.', 'Confirma que o endereço de email está correto.': 'Check that the email address is correct.', 'Não foi possível concluir a operação. Tenta novamente.': 'Could not complete the operation. Try again.',
  'Falta configurar o Neon': 'Neon setup required', 'A carregar a tua sessão...': 'Loading your session...', 'A preparar o teu perfil...': 'Preparing your profile...', 'Não foi possível carregar o perfil': 'Could not load profile', 'Tentar novamente': 'Try again', 'Utilizador': 'User', 'Idioma': 'Language',
  'Nome em inglês (opcional)': 'English name (optional)',
  'Preparação em inglês (opcional)': 'English method (optional)', 'Observações (opcional)': 'Notes (optional)', 'Observações em inglês (opcional)': 'English notes (optional)', 'Ex.: substituições, sugestões ou informação adicional...': 'E.g. substitutions, serving suggestions or extra information...',
  'Dia': 'Day', 'Semana': 'Week', 'Semana atual': 'Current week', 'Semana anterior': 'Previous week', 'Semana seguinte': 'Next week', 'Sem refeições': 'No meals', 'Ver dia': 'View day',
  'Estado': 'Status', 'Planeada': 'Planned', 'Consumida': 'Consumed', 'Marcar como consumida': 'Mark as consumed', 'Marcar como planeada': 'Mark as planned', 'Totais previstos': 'Planned totals',
  'As minhas': 'Mine', 'Públicas': 'Public', 'Duplicar receita': 'Duplicate recipe', 'Receita duplicada com sucesso. A cópia é privada.': 'Recipe duplicated successfully. The copy is private.', 'Não foi possível duplicar a receita.': 'Could not duplicate the recipe.', 'Tradução inglesa completa': 'Complete English translation', 'Tradução inglesa em falta': 'English translation missing', 'Experimenta alterar os filtros ou criar uma receita.': 'Try changing the filters or creating a recipe.', 'prot.': 'prot.', 'hidr.': 'carbs', 'gord.': 'fat',
  'Sobre as receitas': 'About recipes',
  'As macros apresentadas em todas as receitas são por porção.\nEm cada receita está indicado o número de porções que os ingredientes rendem, assim como o tempo médio de preparação (apenas para referência).\nOs ingredientes assinalados como opcionais não estão incluídos nas macros — estão apenas sugeridos para dar mais sabor ou para usares como alternativa a algum ingrediente.\nOs toppings estão incluídos nas macros, excepto quando indicados como opcionais.': 'The macros shown for every recipe are per serving.\nEach recipe shows the number of servings the ingredients make, as well as the average preparation time (for reference only).\nIngredients marked as optional are not included in the macros — they are suggested only for extra flavour or as an alternative to another ingredient.\nToppings are included in the macros unless they are marked as optional.',
} as const;

const savedLanguage = localStorage.getItem('meal-tracker-language');
const initialLanguage = savedLanguage === 'en' || savedLanguage === 'pt' ? savedLanguage : (navigator.language.startsWith('pt') ? 'pt' : 'en');

i18n.use(initReactI18next).init({
  resources: { pt: { translation: {} }, en: { translation: english } },
  lng: initialLanguage, fallbackLng: 'pt', interpolation: { escapeValue: false },
  returnNull: false,
});
document.documentElement.lang = initialLanguage;
i18n.on('languageChanged', (language) => { document.documentElement.lang = language; });

export async function changeLanguage(language: 'pt' | 'en') {
  localStorage.setItem('meal-tracker-language', language);
  await i18n.changeLanguage(language);
}

export default i18n;
