import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const english = {
  'Nutrição sem complicações': 'Nutrition made simple', 'Resumo': 'Overview', 'Receitas': 'Recipes', 'Diário': 'Diary', 'Definições': 'Settings', 'Terminar sessão': 'Sign out',
  'O teu dia nutricional': 'Your nutrition today', 'Olá! O que vamos comer?': 'Hello! What are we eating?', 'Acompanha as refeições e mantém os teus objetivos à vista.': 'Track your meals and keep your goals in sight.', 'Registar refeição': 'Log meal', 'Calorias restantes': 'Calories remaining', 'Consumiste {{consumed}} das {{goal}} kcal planeadas.': 'You consumed {{consumed}} of {{goal}} planned kcal.', 'Macronutrientes': 'Macronutrients', 'Proteína': 'Protein', 'Hidratos': 'Carbs', 'Gordura': 'Fat', 'Refeições de hoje': "Today's meals", '{{count}} registo(s)': '{{count}} entry', '{{count}} registo(s)_plural': '{{count}} entries', 'Ainda não registaste nenhuma refeição.': "You haven't logged any meals yet.", 'Ver diário': 'View diary', 'Pesquisa uma receita para começares o teu dia.': 'Find a recipe to start your day.', '{{count}} porção(ões)': '{{count}} serving', '{{count}} porção(ões)_plural': '{{count}} servings',
  'Histórico': 'History', 'Diário de refeições': 'Meal diary', 'Consulta e gere tudo o que registaste.': 'View and manage everything you have logged.', 'Compras': 'Shopping', 'Planeamento': 'Planning', 'Lista de compras': 'Shopping list', 'Adiciona as refeições que queres comprar a partir da vista semanal do diário.': 'Add the meals you want to shop for from the weekly diary view.', '{{count}} refeição(ões) adicionada(s)': '{{count}} meal added', '{{count}} refeição(ões) adicionada(s)_plural': '{{count}} meals added', '{{count}} refeição(ões) adicionada(s) à lista de compras.': '{{count}} meal added to your shopping list.', '{{count}} refeição(ões) adicionada(s) à lista de compras._plural': '{{count}} meals added to your shopping list.', '{{count}} ingrediente(s) na lista': '{{count}} ingredient on the list', '{{count}} ingrediente(s) na lista_plural': '{{count}} ingredients on the list', '{{count}} receita(s) planeada(s)': '{{count}} planned recipe', '{{count}} receita(s) planeada(s)_plural': '{{count}} planned recipes', 'Por receita': 'By recipe', 'Limpar itens assinalados': 'Clear checked items', 'Limpar lista': 'Clear list', 'A lista de compras está vazia': 'Your shopping list is empty', 'Abre a vista semanal do diário e adiciona as refeições futuras que queres comprar.': 'Open the weekly diary view and add the future meals you want to shop for.', 'Adicionar semana às compras': 'Add week to shopping list', 'Não existem refeições futuras nesta semana.': 'There are no future meals this week.', 'Ainda não tens refeições planeadas': 'You do not have any planned meals yet', 'Regista receitas numa data futura para criares automaticamente a lista de compras.': 'Log recipes on a future date to automatically create your shopping list.', 'Ver receitas': 'View recipes', 'Marcar ingrediente {{name}}': 'Mark {{name}}', 'Ingredientes com g, kg, ml ou L são somados automaticamente quando o nome é igual.': 'Ingredients with g, kg, ml or L are automatically totalled when their name matches.', 'Calorias': 'Calories', 'Sem registos.': 'No entries.', 'Editar registo': 'Edit entry', 'Remover refeição': 'Remove meal', 'Não foi possível apagar o registo.': 'Could not delete the entry.',
  'Adicionar à lista de compras': 'Add to shopping list', 'Receita adicionada à lista de compras.': 'Recipe added to the shopping list.', 'Não foi possível adicionar a receita à lista de compras.': 'Could not add the recipe to the shopping list.', 'Adicionada diretamente': 'Added directly', 'Remover receita da lista': 'Remove recipe from list',
  'Pequeno-almoço': 'Breakfast', 'Almoço': 'Lunch', 'Lanche': 'Snack', 'Jantar': 'Dinner', 'Pequeno Almoço': 'Breakfast', 'Almoço/Jantar': 'Lunch/Dinner', 'Snacks': 'Snacks',
  'Dia da refeição': 'Meal date', 'Hoje': 'Today', 'Ontem': 'Yesterday', 'Como ainda é antes das 04:00, sugerimos o dia anterior. Podes alterar se necessário.': 'Since it is before 4:00 AM, we suggest the previous day. You can change it if needed.', 'Tipo de refeição': 'Meal type', 'Número de porções': 'Number of servings', 'proteína': 'protein', 'hidratos': 'carbs', 'gordura': 'fat', 'Registo alterado com sucesso.': 'Entry updated successfully.', 'Refeição registada com sucesso.': 'Meal logged successfully.', 'Não foi possível registar a refeição.': 'Could not log the meal.', 'Alterações guardadas': 'Changes saved', 'Registado': 'Logged', 'Guardar alterações': 'Save changes', 'Adicionar ao diário': 'Add to diary',
  'Biblioteca': 'Library', 'Encontra a próxima refeição': 'Find your next meal', 'Pesquisa pelo nome da receita ou por um ingrediente.': 'Search by recipe name or ingredient.', 'Nova receita': 'New recipe', 'Ex.: frango, aveia, salmão...': 'E.g. chicken, oats, salmon...', 'Todas': 'All', '{{count}} receita(s) encontrada(s)': '{{count}} recipe found', '{{count}} receita(s) encontrada(s)_plural': '{{count}} recipes found', 'A carregar receitas...': 'Loading recipes...', 'Ainda não existem receitas': 'There are no recipes yet', 'Cria a primeira receita para começares.': 'Create the first recipe to get started.', 'Ver': 'View', 'Registar': 'Log', 'Ver receita {{name}}': 'View {{name}} recipe', 'Editar receita': 'Edit recipe', 'Apagar receita': 'Delete recipe', 'A apagar...': 'Deleting...', 'Apagar “{{name}}”?': 'Delete “{{name}}”?', 'Não foi possível apagar.': 'Could not delete.',
  'Voltar às receitas': 'Back to recipes', 'Editar': 'Edit', 'Ingredientes': 'Ingredients', 'Preparação': 'Method', 'Observações': 'Notes', 'Ainda não foram adicionadas instruções de preparação.': 'No preparation instructions have been added yet.', 'A carregar receita...': 'Loading recipe...',
  'Cria uma receita': 'Create a recipe', 'Nome': 'Name', 'Categoria': 'Category', 'Tempo de preparação (min)': 'Preparation time (min)', 'Imagem da receita': 'Recipe image', '(opcional)': '(optional)', 'Opcional': 'Optional', 'Pré-visualização da receita': 'Recipe preview', 'Remover imagem': 'Remove image', 'Escolher uma imagem': 'Choose a recipe image', 'JPEG, PNG ou WebP · máximo 5 MB': 'JPEG, PNG or WebP · maximum 5 MB', 'Substituir imagem': 'Replace image', 'Valores por porção': 'Values per serving', 'Adicionar': 'Add', 'Quantidade': 'Quantity', 'Unidade': 'Unit', 'Ingrediente (PT)': 'Ingredient (PT)', 'Ingrediente (EN)': 'Ingredient (EN)', 'Ingrediente {{number}}': 'Ingredient {{number}}', 'Descreve os passos de preparação...': 'Describe the preparation steps...', 'Tornar receita pública': 'Make recipe public', 'Outros utilizadores poderão encontrá-la, mas apenas tu poderás alterá-la.': 'Other users will be able to find it, but only you can edit it.', 'A guardar...': 'Saving...', 'Criar receita': 'Create recipe', 'A autenticação não está configurada.': 'Authentication is not configured.', 'A tua sessão expirou. Inicia sessão novamente.': 'Your session has expired. Sign in again.', 'Não foi possível guardar a receita.': 'Could not save the recipe.', 'Escolhe uma imagem JPEG, PNG ou WebP.': 'Choose a JPEG, PNG or WebP image.', 'A imagem não pode ter mais de 5 MB.': 'The image cannot exceed 5 MB.',
  'Preferências': 'Preferences', 'Atualiza os teus dados, recalcula o plano ou define objetivos manualmente.': 'Update your details, recalculate your plan or set goals manually.', 'Vamos personalizar o teu plano': "Let's personalize your plan", 'Responde a algumas perguntas para estimarmos os teus objetivos.': 'Answer a few questions so we can estimate your goals.', 'Criar o meu plano': 'Create my plan',
  'Ano de nascimento': 'Year of birth', 'Fórmula metabólica': 'Metabolic formula', 'Feminina': 'Female', 'Masculina': 'Male', 'Altura (cm)': 'Height (cm)', 'Peso atual (kg)': 'Current weight (kg)', 'Nível de atividade': 'Activity level', 'Sedentário': 'Sedentary', 'Ligeiramente ativo (1–3 dias/semana)': 'Lightly active (1–3 days/week)', 'Moderadamente ativo (3–5 dias/semana)': 'Moderately active (3–5 days/week)', 'Muito ativo (6–7 dias/semana)': 'Very active (6–7 days/week)', 'Extremamente ativo': 'Extremely active', 'Objetivo': 'Goal', 'Perder peso gradualmente': 'Lose weight gradually', 'Manter o peso': 'Maintain weight', 'Ganhar peso gradualmente': 'Gain weight gradually', 'Como queres definir os teus objetivos diários?': 'How would you like to set your daily goals?', 'Podemos estimá-los com as respostas acima ou podes introduzir um plano que já tenhas definido.': 'We can estimate them from your answers or you can enter an existing plan.', 'Calcular por mim': 'Calculate for me', 'Usar idade, corpo, atividade e objetivo.': 'Use age, body, activity and goal.', 'Já tenho valores definidos': 'I already have target values', 'Introduzir calorias e macros manualmente.': 'Enter calories and macros manually.', 'Os teus objetivos diários': 'Your daily goals', 'Objetivos diários estimados': 'Estimated daily goals', 'Introduz os valores do teu plano atual.': 'Enter the values from your current plan.', 'Calculados a partir das respostas acima.': 'Calculated from the answers above.', 'Ao alterar as calorias, proteína, hidratos e gordura são recalculados com base no teu peso e na nova meta calórica. Depois podes editar cada macro individualmente.': 'When calories change, protein, carbs and fat are recalculated using your weight and new calorie target. You can then edit each macro individually.', 'Estimativa para adultos saudáveis baseada em equações populacionais. Necessidades reais podem variar; gravidez, amamentação, condições clínicas ou histórico de perturbações alimentares requerem acompanhamento profissional.': 'Estimate for healthy adults based on population equations. Actual needs may vary; pregnancy, breastfeeding, medical conditions or a history of eating disorders require professional guidance.', 'Alterações guardadas com sucesso.': 'Changes saved successfully.', 'Não foi possível guardar as alterações.': 'Could not save changes.', 'Fechar notificação': 'Close notification',
  'Bem-vinda de volta': 'Welcome back', 'Cria a tua conta': 'Create your account', 'Iniciar sessão': 'Sign in', 'Começar agora': 'Get started', 'Acede às tuas receitas e ao diário de refeições.': 'Access your recipes and meal diary.', 'Guarda os teus objetivos e acompanha cada refeição.': 'Save your goals and track every meal.', 'O teu nome': 'Your name', 'Palavra-passe': 'Password', 'Mínimo de 8 caracteres': 'At least 8 characters', 'Esconder palavra-passe': 'Hide password', 'Mostrar palavra-passe': 'Show password', 'Entrar': 'Sign in', 'Criar conta': 'Create account', 'Ainda não tens conta?': "Don't have an account yet?", 'Já tens uma conta?': 'Already have an account?', 'Regista-te': 'Sign up', 'Inicia sessão': 'Sign in', 'Não foi possível contactar o serviço de autenticação. Tenta novamente.': 'Could not contact the authentication service. Try again.', 'Email ou palavra-passe incorretos.': 'Incorrect email or password.', 'Já existe uma conta com este email.': 'An account with this email already exists.', 'Confirma que o endereço de email está correto.': 'Check that the email address is correct.', 'Não foi possível concluir a operação. Tenta novamente.': 'Could not complete the operation. Try again.',
  'Falta configurar o Neon': 'Neon setup required', 'A carregar a tua sessão...': 'Loading your session...', 'A preparar o teu perfil...': 'Preparing your profile...', 'Não foi possível carregar o perfil': 'Could not load profile', 'Tentar novamente': 'Try again', 'Utilizador': 'User', 'Idioma': 'Language',
  'Nome em inglês (opcional)': 'English name (optional)',
  'Preparação em inglês (opcional)': 'English method (optional)', 'Observações (opcional)': 'Notes (optional)', 'Observações em inglês (opcional)': 'English notes (optional)', 'Ex.: substituições, sugestões ou informação adicional...': 'E.g. substitutions, serving suggestions or extra information...',
  'Dia': 'Day', 'Semana': 'Week', 'Semana atual': 'Current week', 'Semana anterior': 'Previous week', 'Semana seguinte': 'Next week', 'Sem refeições': 'No meals', 'Ver dia': 'View day',
  'Estado': 'Status', 'Planeada': 'Planned', 'Consumida': 'Consumed', 'Marcar como consumida': 'Mark as consumed', 'Marcar como planeada': 'Mark as planned', 'Totais previstos': 'Planned totals',
  'As minhas': 'Mine', 'Públicas': 'Public', 'Duplicar receita': 'Duplicate recipe', 'Receita duplicada com sucesso. A cópia é privada.': 'Recipe duplicated successfully. The copy is private.', 'Não foi possível duplicar a receita.': 'Could not duplicate the recipe.', 'Tradução inglesa completa': 'Complete English translation', 'Tradução inglesa em falta': 'English translation missing', 'Experimenta alterar os filtros ou criar uma receita.': 'Try changing the filters or creating a recipe.', 'prot.': 'prot.', 'hidr.': 'carbs', 'gord.': 'fat',
  'Sobre as receitas': 'About recipes',
  'As macros apresentadas em todas as receitas são por porção.\nEm cada receita está indicado o número de porções que os ingredientes rendem, assim como o tempo médio de preparação (apenas para referência).\nOs ingredientes assinalados como opcionais não estão incluídos nas macros — estão apenas sugeridos para dar mais sabor ou para usares como alternativa a algum ingrediente.\nOs toppings estão incluídos nas macros, excepto quando indicados como opcionais.': 'The macros shown for every recipe are per serving.\nEach recipe shows the number of servings the ingredients make, as well as the average preparation time (for reference only).\nIngredients marked as optional are not included in the macros — they are suggested only for extra flavour or as an alternative to another ingredient.\nToppings are included in the macros unless they are marked as optional.',
} as const;

const savedLanguage = localStorage.getItem('meal-tracker-language');
const initialLanguage = savedLanguage === 'en' || savedLanguage === 'pt' ? savedLanguage : (navigator.language.startsWith('pt') ? 'pt' : 'en');

i18n.use(initReactI18next).init({
  resources: { pt: { translation: {} }, en: { translation: english } },
  lng: initialLanguage, fallbackLng: 'pt', interpolation: { escapeValue: false },
  returnNull: false,
});
document.documentElement.lang = initialLanguage;
i18n.on('languageChanged', (language) => { document.documentElement.lang = language; });

export async function changeLanguage(language: 'pt' | 'en') {
  localStorage.setItem('meal-tracker-language', language);
  await i18n.changeLanguage(language);
}

export default i18n;
